import Link from "next/link";
import { ArrowRight, Check, KeyRound, ShieldCheck, Terminal, Users } from "lucide-react";
import Brand from "@/components/brand";
import ThemeToggle from "@/components/theme-toggle";
import { account, firstName } from "@/lib/server-api";
export default async function Home() {
  const user = await account();
  return <div className="site-page"><header className="site-header"><Brand /><nav><a href="#product">Product</a><a href="#security">Security</a><a href="#pricing">Pricing</a></nav><div className="header-actions"><ThemeToggle />{user ? <><span className="welcome">Welcome back, {firstName(user.Email)}</span><Link className="button primary" href="/dashboard">Go to dashboard</Link></> : <><Link className="button ghost" href="/auth">Sign in</Link><Link className="button primary" href="/auth">Get started</Link></>}</div></header><main>
    <section className="hero"><div className="hero-copy"><span className="kicker">Secrets management for developers</span><h1>Ship without passing secrets around.</h1><p>Envi keeps environment variables encrypted, versioned, and scoped across local development, production, and your team.</p><div className="hero-actions"><Link className="button primary large" href={user ? "/dashboard" : "/auth"}>{user ? "Go to dashboard" : "Start with Envi"}<ArrowRight /></Link><a className="button secondary large" href="#product">See how it works</a></div><div className="proof"><span><Check />Encrypted at rest</span><span><Check />Explicit production access</span><span><Check />CLI and web</span></div></div><div className="product-preview"><div className="preview-top"><span>api-platform</span><b>production</b></div><div className="preview-row"><code>DATABASE_URL</code><span>••••••••••••••••</span></div><div className="preview-row"><code>STRIPE_SECRET_KEY</code><span>••••••••••••••••</span></div><div className="preview-row"><code>REDIS_URL</code><span>••••••••••••••••</span></div><div className="command"><Terminal />$ envi pull</div></div></section>
    <section className="feature-band" id="product"><article><KeyRound /><h2>One source of truth</h2><p>Manage secrets from the dashboard or use the same projects and environments from the CLI.</p></article><article><Users /><h2>Share the project</h2><p>Grant read, write, or manage access without opening your entire workspace.</p></article><article id="security"><ShieldCheck /><h2>Production stays explicit</h2><p>Production environments require direct grants, reducing accidental access and changes.</p></article></section>
    <section className="workflow"><div><span className="kicker">Built around the workflow</span><h2>Local when you want speed. Web when you want visibility.</h2></div><ol><li><b>01</b><span><strong>Create a project</strong>Set up environments from the dashboard or with <code>envi init</code>.</span></li><li><b>02</b><span><strong>Push encrypted values</strong>Versioned updates make concurrent changes visible.</span></li><li><b>03</b><span><strong>Control access</strong>Invite collaborators and keep an audit trail.</span></li></ol></section>
    <section className="pricing" id="pricing"><span className="kicker">Simple pricing</span><h2>Start free. Upgrade when the team grows.</h2><div><strong>$0</strong><span>for personal projects</span><Link className="button primary" href={user ? "/dashboard" : "/auth"}>Get started</Link></div></section>
  </main><footer><Brand /><span>Secrets workflow for modern teams.</span></footer></div>;
}
