"use client";
/* eslint-disable @typescript-eslint/no-unused-expressions */
import { Activity, Clipboard, Eye, EyeOff, Folder, KeyRound, Plus, RefreshCw, Trash2, UserPlus } from "lucide-react";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { filterKeys } from "../utils";
type Project={ID:string;OrgID:string;Name:string}; type Env={ID:string;Name:string;Production:boolean}; type Snap={values:Record<string,string>;revision:number}; type Event={action:string;target_type:string;target_id:string};
async function api<T>(path:string,init:RequestInit={}){const r=await fetch("/api/envi"+path,{...init,headers:{"Content-Type":"application/json",...init.headers}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Request failed");return b as T}
export default function Workspace({page}:{page:"overview"|"secrets"|"projects"|"sharing"|"activity"}){
 const[projects,setProjects]=useState<Project[]>([]),[project,setProject]=useState<Project>(),[envs,setEnvs]=useState<Env[]>([]),[env,setEnv]=useState<Env>(),[snap,setSnap]=useState<Snap>({values:{},revision:0}),[events,setEvents]=useState<Event[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[query,setQuery]=useState(""),[reveal,setReveal]=useState(new Set<string>()),[modal,setModal]=useState<"project"|"env"|"secret"|"share">();
 const loadProjects=useCallback(()=>api<Project[]>("/projects").then(x=>{setProjects(x||[]);setProject(p=>x.find(i=>i.ID===p?.ID)||x[0])}).catch(e=>setError(e.message)),[]);useEffect(()=>{void loadProjects()},[loadProjects]);
 useEffect(()=>{if(project)api<Env[]>(`/projects/${project.ID}/environments`).then(x=>{setEnvs(x||[]);setEnv(e=>x.find(i=>i.ID===e?.ID)||x[0])}).catch(e=>setError(e.message))},[project]);
 const loadSecrets=useCallback(()=>{if(env)api<Snap>(`/environments/${env.ID}/secrets/snapshot`).then(setSnap).catch(e=>setError(e.message))},[env]);useEffect(()=>{void loadSecrets()},[loadSecrets]);
 useEffect(()=>{if(page==="activity"&&project)api<Event[]>(`/orgs/${project.OrgID}/audit-events`).then(setEvents).catch(e=>setError(e.message))},[page,project]);
 const keys=useMemo(()=>filterKeys(snap.values,query),[snap,query]);
 async function submit(type:string,data:Record<string,string>){if(type==="project"){const me=await api<{OrganizationID:string}>("/me");await api("/projects",{method:"POST",body:JSON.stringify({org_id:me.OrganizationID,name:data.name})});await loadProjects()}if(type==="env"&&project){await api(`/projects/${project.ID}/environments`,{method:"POST",body:JSON.stringify({name:data.name,is_production:data.production==="true"})});setProject({...project})}if(type==="secret"&&env){const values={...snap.values,[data.key]:data.value};const x=await api<{revision:number}>(`/environments/${env.ID}/secrets/snapshot`,{method:"PUT",body:JSON.stringify({values,expected_revision:snap.revision})});setSnap({values,revision:x.revision})}if(type==="share"&&project&&env){const x=await api<{Token:string}>(`/projects/${project.ID}/invitations`,{method:"POST",body:JSON.stringify({email:data.email,environment_id:env.ID,permission:data.permission})});setNotice(`Invitation token: ${x.Token}`)}setModal(undefined)}
 const title={overview:"Overview",secrets:"Secrets",projects:"Projects",sharing:"Sharing",activity:"Activity"}[page];
 return <main className="product-page"><div className="page-title"><div><span>Workspace</span><h1>{title}</h1><p>{page==="secrets"?"Encrypted values for the selected environment.":page==="projects"?"Projects and their deployment environments.":page==="sharing"?"Project-level collaborator access.":page==="activity"?"Recent reads and changes.":"Your Envi workspace at a glance."}</p></div>{page==="secrets"&&<button className="button primary" onClick={()=>setModal("secret")}><Plus/>Add secret</button>}{page==="projects"&&<button className="button primary" onClick={()=>setModal("project")}><Plus/>New project</button>}{page==="sharing"&&<button className="button primary" onClick={()=>setModal("share")}><UserPlus/>Invite</button>}</div>
  <div className="scope-bar"><label>Project<select value={project?.ID||""} onChange={e=>setProject(projects.find(p=>p.ID===e.target.value))}>{projects.map(p=><option key={p.ID} value={p.ID}>{p.Name}</option>)}</select></label><label>Environment<select value={env?.ID||""} onChange={e=>setEnv(envs.find(x=>x.ID===e.target.value))}>{envs.map(x=><option key={x.ID} value={x.ID}>{x.Name}</option>)}</select></label>{env?.Production&&<span className="production-tag">Production</span>}</div>{error&&<div className="alert error">{error}</div>}{notice&&<div className="alert notice"><code>{notice}</code></div>}
  {page==="overview"&&<div className="stats"><article><span>Projects</span><strong>{projects.length}</strong></article><article><span>Environments</span><strong>{envs.length}</strong></article><article><span>Secrets</span><strong>{Object.keys(snap.values).length}</strong></article></div>}
  {page==="secrets"&&<section className="table-panel"><div className="table-toolbar"><input placeholder="Filter secret keys" value={query} onChange={e=>setQuery(e.target.value)}/><button className="button secondary" onClick={()=>loadSecrets()}><RefreshCw/>Refresh</button></div><div className="data-table"><div className="data-head"><span>Key</span><span>Value</span><span>Revision</span><span/></div>{keys.map(k=><div className={env?.Production?"data-row production-row":"data-row"} key={k}><code>{k}</code><code>{reveal.has(k)?snap.values[k]:"••••••••••••"}</code><span>{snap.revision}</span><div><button onClick={()=>{const n=new Set(reveal);n.has(k)?n.delete(k):n.add(k);setReveal(n)}}>{reveal.has(k)?<EyeOff/>:<Eye/>}</button><button onClick={()=>navigator.clipboard.writeText(snap.values[k])}><Clipboard/></button><button onClick={async()=>{if(env&&confirm(`Delete ${k}?`)){await api(`/environments/${env.ID}/secrets/${encodeURIComponent(k)}`,{method:"DELETE"});loadSecrets()}}}><Trash2/></button></div></div>)}</div>{!keys.length&&<Empty icon={<KeyRound/>} text="No secrets in this environment."/>}</section>}
  {page==="projects"&&<section className="list-panel">{projects.map(p=><button key={p.ID} onClick={()=>setProject(p)}><Folder/><span><strong>{p.Name}</strong><small>{p.ID}</small></span></button>)}<button onClick={()=>setModal("env")} disabled={!project}><Plus/><span><strong>Add environment</strong><small>to {project?.Name}</small></span></button></section>}
  {page==="sharing"&&<section className="plain-section"><UsersBlock/><button className="button primary" onClick={()=>setModal("share")}><UserPlus/>Invite collaborator</button></section>}
  {page==="activity"&&<section className="list-panel">{events.map((x,i)=><div className="event-row" key={i}><Activity/><span><strong>{x.action.replace("secret.","Secret ")}</strong><small>{x.target_type} · {x.target_id.slice(0,8)}</small></span></div>)}{!events.length&&<Empty icon={<Activity/>} text="No activity yet."/>}</section>}
  {modal&&<Dialog title={{project:"New project",env:"New environment",secret:"Add secret",share:"Invite collaborator"}[modal]} close={()=>setModal(undefined)} submit={d=>submit(modal,d)} type={modal}/>}</main>
}
function Empty({icon,text}:{icon:React.ReactNode;text:string}){return <div className="empty">{icon}<strong>{text}</strong></div>}
function UsersBlock(){return <div><h2>Invite only where access is needed.</h2><p>Choose an environment and grant read, write, or manage permission. Production access remains explicit.</p></div>}
function Dialog({title,close,submit,type}:{title:string;close:()=>void;submit:(d:Record<string,string>)=>Promise<void>;type:string}){const[error,setError]=useState("");return <div className="dialog-backdrop" onMouseDown={close}><form className="dialog" onMouseDown={e=>e.stopPropagation()} onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();try{await submit(Object.fromEntries(new FormData(e.currentTarget).entries())as Record<string,string>)}catch(x){setError((x as Error).message)}}}><header><h2>{title}</h2><button type="button" onClick={close}>×</button></header>{type==="project"&&<Field name="name" label="Project name"/>}{type==="env"&&<><Field name="name" label="Environment name"/><label className="checkbox"><input type="checkbox" name="production" value="true"/>Production environment</label></>}{type==="secret"&&<><Field name="key" label="Secret key"/><Field name="value" label="Secret value"/></>}{type==="share"&&<><Field name="email" label="Email" type="email"/><label>Permission<select name="permission"><option>read</option><option>write</option><option>manage</option></select></label></>}{error&&<p className="form-error">{error}</p>}<button className="button primary">Save</button></form></div>}
function Field({name,label,type="text"}:{name:string;label:string;type?:string}){return <label>{label}<input required name={name} type={type}/></label>}
